export const bibleVersions = [
    { "value": "eng-ESV", "name": "English Standard Version", "lang_name": "English (US)" },
    { "value": "eng-KJVA", "name": "King James Version, American Edition", "lang_name": "English (US)" },
//    { "value": "eng-KJVA", "name": "King James Version with Apocrypha, American Edition", "lang_name": "English (US)" },
    { "value": "eng-NASB", "name": "New American Standard Bible", "lang_name": "English (US)" },
    { "value": "eng-MSG", "name": "The Message", "lang_name": "English (US)" },
    { "value": "eng-AMP", "name": "Amplified Bible", "lang_name": "English (US)" },
    { "value": "eng-CEV", "name": "Contemporary English Version (US Version)", "lang_name": "English (US)" },
    { "value": "eng-GNTD", "name": "Good News Translation (US Version)", "lang_name": "English (US)" },
    // { "value": "eng-CEVD", "name": "Contemporary English Version (US Version)", "lang_name": "English (US)" },

    { "value": "eng-CEVUK", "name": "Contemporary English Version (Anglicised Version)", "lang_name": "English (British)" },
    { "value": "eng-GNBDC", "name": "Good News Bible (Anglicised)", "lang_name": "English (British)" },
    { "value": "eng-KJV", "name": "King James Version", "lang_name": "English (British)" },

    { "value": "aai-AAINT", "name": "Tur gewasin o baibasit boubun", "lang_name": "Arifama-Miniafia" },
    { "value": "aau-AAUNT", "name": "God so Sokior-ok Iwon", "lang_name": "Abau" },
    { "value": "abt-ABTNT", "name": "Gotna Kudi", "lang_name": "Ambulas" },
    { "value": "abt-ABTWNT", "name": "Gotna kundi", "lang_name": "Ambulas" },
    { "value": "aby-ABYNT", "name": "Godinu irau wake", "lang_name": "Aneme Wake" },
    { "value": "acf-ACFNT", "name": "Tèstèman nèf-la: Épi an posyòn an liv samz-la", "lang_name": "Saint Lucian Creole French" },
    { "value": "acr-ACRNNT", "name": "Ri utzilaj tzij re ri kanimajawal Jesucristo", "lang_name": "Achi'" },
    { "value": "acr-ACRNT", "name": "I 'utz laj tzij re i dios", "lang_name": "Achi'" },
    { "value": "acr-ACRTNT", "name": "Ri utzilaj tzij re ri kanimajawal Jesucristo", "lang_name": "Achi'" },
    { "value": "acu-ACUNT", "name": "Yuse chichame aarmauri; Yaanchuik, Chicham; Yamaram Chicham", "lang_name": "Achuar-Shiwiar" },
    { "value": "agr-AGRNT", "name": "Yamajam chicham apajuinu", "lang_name": "Aguaruna" },
    { "value": "agu-AGUBI", "name": "Yi Antiw Bible / Yi Ac'aj Testament", "lang_name": "Aguacateco" },
    { "value": "agu-AGUNT", "name": "Yi Antiw Testament / Yi Ac'aj Testament", "lang_name": "Aguacateco" },
    { "value": "ake-AKENT", "name": "Wakʉ Itekare: Emenna' Pe Ekonekan Nɨto'", "lang_name": "Akawaio" },
    { "value": "alp-ALPNT", "name": "Janji beluke", "lang_name": "Alune" },
    { "value": "ame-AMENT", "name": "Yompor Poʼñoñ ñeñt ̃ attõ Yepartseshar Jesucristo eʼñe etserra aʼpoctaterrnay Yomporesho", "lang_name": "Yanesha'" },
    { "value": "amr-AMRNT", "name": "Jesucristo oy oa’pak: Kenda Jesucristoa; monigka’uyatenok; Diostaj mo’manopo’yarea’ika’ne", "lang_name": "Amarakaeri" },
    { "value": "amu-AMUNT", "name": "Ñʼoom xco na tqueⁿ tyʼo̱o̱tsʼom cantxja ʼnaaʼ Jesucristo", "lang_name": "Guerrero Amuzgo" },
    { "value": "anv-ANVNT", "name": "Ŋwɛ menomenyɛɛ́ mekɛ́", "lang_name": "Denya" },
    { "value": "apn-APNNT", "name": "Tĩrtũm kapẽr ã kagà nyw", "lang_name": "Apinayé" },
    { "value": "apu-APUNT", "name": "Teoso sãkire amaneri", "lang_name": "Apurinã" },
    { "value": "apw-APWNT", "name": "The New Testament of our Lord and Saviour Jesus Christ", "lang_name": "Western Apache" },
    { "value": "apy-APYNT", "name": "Ritonõpo Omiry", "lang_name": "Apalaí" },
    { "value": "arl-ARLNT", "name": "Quiarinio pueyaso rupaa pa jiyaniijia Jesucristojiniji pueyano rupaajinia", "lang_name": "Arabela" },
    { "value": "arn-ARNNT", "name": "Ngünechen ñi Küme Dungu", "lang_name": "Mapudungun" },
    { "value": "auc-AUCNT", "name": "Wængonguï nänö Apæ̈negaïnö", "lang_name": "Waorani" },
    { "value": "auy-AUYNT", "name": "Aú-aai símai kááisamakain-aai", "lang_name": "Awiyaana" },
    { "value": "azg-AZGNT", "name": "Jnʼoon xco na tquen tyoʼtsʼon", "lang_name": "San Pedro Amuzgos Amuzgo" },
    { "value": "azz-AZZNT", "name": "In cuali tajtoltzin de Dios", "lang_name": "Highland Puebla Nahuatl" },
    { "value": "bao-BAONT", "name": "U̶mʉreco pacʉ wederique", "lang_name": "Waimaha" },
    { "value": "bjr-BJRNT", "name": "Fúka Moodaanaki Kira Ufa Afaqínaasa Ufa", "lang_name": "Binumarien" },
    { "value": "bjv-BJVNT", "name": "KƗLӘ-MƗNDƗ KƗ SƗGƗ", "lang_name": "Bedjond" },
    { "value": "bkq-BKQNT", "name": "Deus Itaumbyry", "lang_name": "Bakairí" },
    { "value": "blz-BLZNT", "name": "Kitap molinas men ringkat na alaata'ala: perjanjian baru", "lang_name": "Balantak" },
    { "value": "bmr-BMRNT", "name": "Moocaani iijɨ", "lang_name": "Muinane" },
    { "value": "bnp-BNPNTP", "name": "A Nitana Vure", "lang_name": "Bola" },
    { "value": "boa-BOANT", "name": "Píívyéébé ihjyu: jetsocríjyodítyú cáátúnuháámɨ", "lang_name": "Bora" },
    { "value": "box-BOXNT", "name": "Dónbeenì páaníi fĩnle vũahṹ", "lang_name": "Buamu" },
    { "value": "bsn-BSNNT", "name": "Dios oca gotirituti", "lang_name": "Barasana-Eduria" },
    { "value": "bss-BSSNT", "name": "Melɛ̌ Mékɔ̄ɔ̄lē", "lang_name": "Akoose" },
    { "value": "bzd-BZDNT", "name": "Tte Pa̱ꞌa̱li̱ Meꞌ Skëköl tö Seꞌ a̱", "lang_name": "Bribri" },
    { "value": "bzd-BZDNTPO", "name": "Tte Pa̱'a̱li̱ Me' Skëköl tö Se' a̱", "lang_name": "Bribri" },
    { "value": "bzj-BZJNT", "name": "Di Nyoo Testiment eena Bileez Kriol", "lang_name": "Belize Kriol English" },
    { "value": "caa-CAANT", "name": "E ojroner xe' imb' utz tua' Cawinquirar Jesucristo", "lang_name": "Chortí" },
    { "value": "cab-CABNT", "name": "Lerérun Búngiu To Lánina Iséri Darádu", "lang_name": "Garifuna" },
    { "value": "caf-CAFNT", "name": "Yakʼusda bughunek: k’andit khunek neba lhaidinla", "lang_name": "Southern Carrier" },
    { "value": "cak-CAKCNT", "name": "Ri C'ac'a Trato ri Xuben ri Dios Quiq'uin ri Vinek", "lang_name": "Cakchiquel" },
    { "value": "cak-CAKENT", "name": "RI DIOS NCH'O PA KACH'ABÜL CHEKE", "lang_name": "Cakchiquel" },
    { "value": "cak-CAKSNT", "name": "Ri c'ac'ac' Testamento pa kach'ab'al", "lang_name": "Cakchiquel" },
    { "value": "cak-CAKWNT", "name": "Ri C'ac'ac' Testamento pa Kach'abel", "lang_name": "Cakchiquel" },
    { "value": "cak-CAKYNT", "name": "Re C'ac'a Testamento pa Kach'abal", "lang_name": "Cakchiquel" },
    { "value": "cao-CAONT", "name": "Dios Chani", "lang_name": "Chácobo" },
    { "value": "cap-CAPNT", "name": "Ew Testamento: Chipay Tawkquiztan", "lang_name": "Puquina" },
    { "value": "car-CARNT", "name": "Asery Tamusi karetary", "lang_name": "Galibi Carib" },
    { "value": "cav-CAVNT", "name": "Yusuja Quisarati", "lang_name": "Cavineña" },
    { "value": "cax-CAXNT", "name": "Manitanati Tuparrü", "lang_name": "Chiquitano" },
    { "value": "cbc-CBCNT", "name": "Dios Cʉ̃ Cauetibʉjʉ Cũrĩcã Tuti", "lang_name": "Carapana" },
    { "value": "cbi-CBINTPO", "name": "Diosa' kiika; Génesis, Éxodo y El Nuevo Testamento", "lang_name": "Chachi" },
    { "value": "cbr-CBRNT", "name": "Nukën 'Ibu Diosan ain unikama 'inan ain bana", "lang_name": "Cashibo-Cacataibo" },
    { "value": "cbs-CBSNT", "name": "Diosun Jesúswen taexun yuba bena yiniki", "lang_name": "Cashinahua" },
    { "value": "cbt-CBTNTPO", "name": "Yosë nanamën", "lang_name": "Chayahuita" },
    { "value": "cbu-CBUNT", "name": "Apanlli Kuku", "lang_name": "Candoshi-Shapra" },
    { "value": "cco-CCONT", "name": "Júu ʼmɨ́ɨ e cacuo fidiée", "lang_name": "Comaltepec Chinantec" },
    { "value": "chd-CHDNT", "name": "Lataiquiʼ loyaʼapa iƚe al cʼa lixpicʼepa L̵anDios", "lang_name": "Highland Oaxaca Chontal" },
    { "value": "chf-CHFNT", "name": "U Chʼuʼul Tʼan Dios (El Nuevo Testamento de nuestro señor Jesucristo en chontal de Tabasco)", "lang_name": "Tabasco Chontal" },
    { "value": "chq-CHQNT", "name": "Juu³ tyʉ² ʼe gafaaʼ²¹ Dios tyaʼ tsá²", "lang_name": "Quiotepec Chinantec" },
    { "value": "chz-CHZNTPS", "name": "Hmooh hmëë he- ga-jmee Jesucristo; Salmos", "lang_name": "Ozumacín Chinantec" },
    { "value": "cjo-CJONT", "name": "Iwaperite tajorentsi ikenkithatakoetziri awinkatharite Jesokirishito: owakirari inimotakiri tajorentsi", "lang_name": "Ashéninka Pajonal" },
    { "value": "cle-CLENT", "name": "Ja̱³la³ fáh⁴dxa⁴²dxú⁴ hi³mɨɨ³² chiáh² Ñúh³a² Jesucristo; Salmos", "lang_name": "Lealao Chinantec" },
    { "value": "cme-CMENT", "name": "Diiloŋ-nelma Tobisĩfɛlɛnni", "lang_name": "Cerma" },
    { "value": "cni-CNINT", "name": "Irineane tasorentsi oquenquetsatacotaqueri Avincatsarite Jesoquirishito", "lang_name": "Asháninka" },
    { "value": "cnl-CNLNT", "name": "Júu² 'mɨɨn³² 'e³ ca²³ŋɨń² Dios", "lang_name": "Lalana Chinantec" },
    { "value": "cnt-CNTNT", "name": "Jag₁ ʼmɨ́₂ a₂ma₂lɨʼ₅₄ quianʼ₅₄ Diu₄", "lang_name": "Tepetotutla Chinantec" },
    { "value": "cof-COFNT", "name": "Diosichi Pila", "lang_name": "Colorado" },
    { "value": "con-CONNTPO", "name": "Chiga Tevaen'Jema Atesuja 1, Aisheve Caña'cho", "lang_name": "Cofán" },
    { "value": "cot-COTNT", "name": "Iroaquerari Itioncacaantaqueca Aapani Irioshi: Tsavetacoquerica Amajirote Jesoquirishito", "lang_name": "Caquinte" },
    { "value": "cpa-CPANT", "name": "El Nuevo Testamento de nuestro señor Jesucristo: Versión chinanteca", "lang_name": "Palantla Chinantec" },
    { "value": "cpb-CPBNT", "name": "Kameethari Ñaantsi: ikenkitha-takoitziri awinkatharite Jesucristo; Owakerari aapatziya-wakagaantsi", "lang_name": "Ucayali-Yurúa Ashéninka" },
    { "value": "cpc-CPCNT", "name": "KAMIITHARI ÑAANTSI", "lang_name": "Ajyíninka Apurucayali" },
    { "value": "cpu-CPUNT", "name": "KAMEETHARI ÑAANTSI: Iñaaventaitzirira Avinkatharite Jesucristo", "lang_name": "Pichis Ashéninka" },
    { "value": "crn-CRNNT", "name": "Ɨ niuucari tɨ jejcua, tɨ ajta jɨme'en ra'axa a'ɨjna ɨ tavastara'a, ɨ Cɨriistu'u tɨ ji'i Jesús tɨ̀ tu'irájtuaa", "lang_name": "El Nayar Cora" },
    { "value": "crx-CRXNTPO", "name": "Yak'usda Ooghuni", "lang_name": "Carrier" },
    { "value": "cso-CSONT", "name": "Jú¹ chú³² quioh²¹ Jesús tsá² lɨn³ Cristo", "lang_name": "Sochiapam Chinantec" },
    { "value": "cta-CTANT", "name": "Chaʼ tsoʼo nu nchcuiʼ jiʼi̱ Jesucristo nu xuʼna na", "lang_name": "Tataltepec Chatino" },
    { "value": "ctp-CTPNT", "name": "Chaʼ suʼwe nu nchkwiʼ chaʼ ʼin Jesucristo nu nka xʼnaan", "lang_name": "Western Highland Chatino" },
    { "value": "ctu-CTUBI", "name": "I T’an Dios", "lang_name": "Chol" },
    { "value": "ctu-CTUNT", "name": "Jini wen bʌ tʼan", "lang_name": "Chol" },
    { "value": "cub-CUBNT", "name": "Majepacʉ jʉ̃menijicʉi yávaiye mamaene coyʉitucubo", "lang_name": "Cubeo" },
    { "value": "cuc-CUCNT", "name": "Jau²³ hm²³ i⁴ra³tya²³ nei² quieh¹ re¹ Jesucristo quian⁴-¹", "lang_name": "Usila Chinantec" },
    { "value": "cui-CUINT", "name": "Nacom Pejume Diwesi", "lang_name": "Cuiba" },
    { "value": "cuk-CUKNT", "name": "Bab dummad Jesucristoba igar mesisad garda", "lang_name": "San Blas Kuna" },
    { "value": "cut-CUTNT", "name": "El Nuevo Testamento: Cuicateco de Teutila", "lang_name": "Teutila Cuicatec" },
    { "value": "cux-CUXNT", "name": "Nduudu nʼdai yeⁿʼe Ndyuūs yeⁿʼe cuicateco yeⁿʼe Tepeuxila", "lang_name": "Tepeuxila Cuicatec" },
    { "value": "cym-BCN", "name": "Beibl Cymraeg Newydd", "lang_name": "Cymraeg" },
    { "value": "cym-BCND", "name": "Beibl Cymraeg Newydd Diwygiedig 2004", "lang_name": "Cymraeg" },
    { "value": "cym-BNET", "name": "beibl.net 2015", "lang_name": "Cymraeg" },
    { "value": "daa-DAANT", "name": "Jamaw ta Marbinto: Kabarre ta Gala ɗo bi ka Iisa Masi iŋ daŋla", "lang_name": "Dangaléat" },
    { "value": "dad-DADNT", "name": "Mata Ifenẽya Nẽ Od", "lang_name": "Marik" },
    { "value": "dik-DIKNT", "name": "Lëk yam", "lang_name": "Dinka: Southwestern" },
    { "value": "djk-DJKNT", "name": "Beibel: okanisi tongo", "lang_name": "Businenge Tongo" },

    { "value": "ese-ESENT", "name": "Eyacuiñajjija Esohui", "lang_name": "Ese Ejja" },
    { "value": "esk-ESKNT", "name": "Ipqitchuat Makpiġaat - Agaayyutim Uqałhi Iñupiatun", "lang_name": "Northwest Alaska Inupiatun" },
    { "value": "fij-FOV", "name": "Vakavakadewa Makawa", "lang_name": "Fijian" },
    { "value": "gng-GNGNT", "name": "Uwien ya Jɔtiefɛ̀nku ya gbɔnku", "lang_name": "Ngangam" },
    { "value": "gnw-GNWNT", "name": "Nuevo Testamento Guaraní Pe", "lang_name": "Guaraní: Western Bolivian" },
    { "value": "gub-GUBBI", "name": "Tupàn zeꞌeg", "lang_name": "Guajajára" },
    { "value": "gui-GUINT", "name": "Nuevo Testamento Guaraní Pe", "lang_name": "Guaraní: Eastern Bolivian" },
    { "value": "gul-GULNT", "name": "De Nyew Testament", "lang_name": "Sea Island Creole English" },
    { "value": "guo-GUONT", "name": "Pajelwʉajan Dios pejjamechan", "lang_name": "Guayabero" },
    { "value": "gwi-GWINT", "name": "Vit'eegwijyąhchy'aa Vagwandak Nizįį", "lang_name": "Gwichʼin" },
    { "value": "gym-GYMNT", "name": "Kukwe kuin ngöbökwe", "lang_name": "Ngäbere" },
    { "value": "gyr-GYRNT", "name": "Tũpa Ñehengagüer", "lang_name": "Guarayu" },
    { "value": "hch-HCHNT", "name": "Cacaüyari niuquieya xapayari türatu hecuame hepaüsita tatiʼaitüvame tasivicueisitüvame Quesusi Cürisitu miʼatüa = El Nuevo Testamento de nuestro señor y salvador Jesucristo", "lang_name": "Huichol" },
    { "value": "hix-HIXNT", "name": "Khoryenkom Karyehtanà", "lang_name": "Hixkaryána" },
    { "value": "hns-HNSNT", "name": "Parmeswar ke naawa poestak", "lang_name": "Caribbean Hindustani" },
    { "value": "hop-HOPNT", "name": "God Lavayiyat Aṅ Puhuvasiwni", "lang_name": "Hopi" },
    { "value": "hrv-HRS07", "name": "Biblija, Sveto pismo Staroga i Novoga zavjeta", "lang_name": "Hrvatski" },
    { "value": "hub-HUBNT", "name": "Yuusa chichame yaunchukia tura yamaram chichamjai aarmau", "lang_name": "Huambisa" },
    { "value": "hus-HUSNT", "name": "An it jilchith cau cʼal i Ajatic Jesucristo", "lang_name": "Huastec" },
    { "value": "huu-HUUNT", "name": "Jusiñamui uai: Jusiñamui jito rafue illa rabenico", "lang_name": "Murui Huitoto" },
    { "value": "huv-HUVNT", "name": "Jayats nanderac wüx miteatiiüts Jesucristo", "lang_name": "San Mateo Del Mar Huave" },
    { "value": "hwc-HWCNT", "name": "Da Jesus Book", "lang_name": "Hawai'i Creole English" },
    { "value": "ign-IGNNT", "name": "Eta Táurinaquene máechajiriruvahi ema Viya eta viyehe, ticaijare puito Eta Nuevo Testamento", "lang_name": "Moxos" },
    { "value": "iou-IOUNTPO", "name": "Anutu Täŋo Man", "lang_name": "Tuma-Irumu" },
    { "value": "ixl-IXLCNT", "name": "Viakʼla txumbʼal u tioxh", "lang_name": "Ixil" },
    { "value": "ixl-IXLNNT", "name": "U ak' Testamento tu kuyob'al", "lang_name": "Ixil" },
    { "value": "jac-JACNT", "name": "Nuevo Testamento yin̈ abxubal", "lang_name": "Jakalteko" },
    { "value": "jic-JICNT", "name": "Dios Tjevele Jupj 'Üsüs La Qjuisiji Jesucristo Mpes", "lang_name": "Tol" },
    { "value": "jiv-JIVNT", "name": "Yus Papí: Shuarja̱i̱ Yus Yamaram Chicham Najanamu", "lang_name": "Shuar" },
    { "value": "jvn-JVNNT", "name": "Kitab sutyi prejanjian anyar ing Basa Jawa Suriname sing gampang", "lang_name": "Caribbean Javanese" },
    { "value": "kaq-KAQNT", "name": "Noquen hihbaan joi", "lang_name": "Capanahua" },
    { "value": "kbc-KBCNT", "name": "Gela Liwai Lotaɡ̶anaɡ̶axi Aneotedoɡ̶oji", "lang_name": "Kadiwéu" },
    { "value": "kdl-KDLNT", "name": "Kazuwamgbani ka savu n Tsikimba n aɓon a ɗa a ɗanga̱sai a kazuwamgbani ka cau", "lang_name": "Tsikimba" },
    { "value": "ken-KENNT", "name": "Ɛkáti Nku Nkɔ", "lang_name": "Kenyang" },
    { "value": "kgk-KGKNT", "name": "Nhandejáry Nhe'ẽ", "lang_name": "Kaiwá" },
    { "value": "kgp-KGPNT", "name": "Topẽ vĩ rá", "lang_name": "Kaingang" },
    { "value": "knj-KNJNT", "name": "Ja' An Nuevo Testamento", "lang_name": "Western Kanjobal" },
    { "value": "kpj-KPJNT", "name": "Deuxu Rybe Tyyriti", "lang_name": "Karajá" },
    { "value": "kvn-KVNNT", "name": "Pab tummad karta pab Jesucristobal igal-pin mezhijad", "lang_name": "Border Kuna" },
    { "value": "kyz-KYZNT", "name": "Janeruwarete 'Ga Je'eg", "lang_name": "Kayabí" },
    { "value": "lac-LACNT", "name": "A quet u t'ʌno' a ricʼbeno'", "lang_name": "Lacandon" },
    { "value": "lif-LIFNT", "name": "ᤏᤡᤱᤘᤠ᤹ᤑᤢ ᤐᤠ᤺ᤴᤈᤠᤰ ᤁᤢᤛᤱ ᤔᤠᤱᤜᤢᤵ", "lang_name": "Limbu" },
    { "value": "maa-MAANT", "name": "'Én Xiṯ se-la̱ Nainá ra a̱'ta 'tse̱ Jesucristo", "lang_name": "San Jerónimo Tecóatl Mazatec" },
    { "value": "maj-MAJNT", "name": "Éhe̱n Nti̱a̱ná", "lang_name": "Jalapa De Díaz Mazatec" },
    { "value": "mam-MAMNT", "name": "Acʼaj testamento (El Nuevo testamento in Mam de Todos Santos)", "lang_name": "Mam" },
    { "value": "maq-MAQNT", "name": "Compromisu xi majo xi casahmi nina cojo xuta (El Nuevo Testamento en el mazateco de Chiquihuitlán de Juárez ... y en español)", "lang_name": "Chiquihuitlán Mazatec" },
    { "value": "mau-MAUNT", "name": "Xon⁴-le⁴ ni³na¹ xi³ tʔa³tsʔe⁴ Jesucristo", "lang_name": "Huautla Mazatec" },
    { "value": "mav-MAVNT", "name": "Tupana Ehay Satere Mawe Pusupuo", "lang_name": "Sateré-Mawé" },
    { "value": "maz-MAZNT", "name": "Nu o̱ jña mizhocjimi nu mama ja ga cja e Jesucristo", "lang_name": "Central Mazahua" },
    { "value": "mbc-MBCNT", "name": "Amenan pe paapaya uyetato'kon", "lang_name": "Macushi" },
    { "value": "mbj-MBJNT", "name": "Pꞌop Hagä Do Panyyg Hanäm Do Hahỹỹh", "lang_name": "Nadëb" },
    { "value": "mbl-MBLNT", "name": "Topa Yõg Tappet", "lang_name": "Maxakalí" },
    { "value": "mcb-MCBNT", "name": "Iriniane Tasorintsi", "lang_name": "Machiguenga" },
    { "value": "mcd-MCDNT", "name": "Diospan Tsain", "lang_name": "Sharanahua" },
    { "value": "mcf-MCFNT", "name": "Esuquidistu Chuiquin Tantiamete", "lang_name": "Matsés" },
    { "value": "mco-MCONT", "name": "El Nuevo Testamento en mixe de Coatlán", "lang_name": "Mixe: Coatlán" },
    { "value": "mib-MIBNT", "name": "Nuevo Testamento en mixteco", "lang_name": "Mixtec: Atatláhuca" },
    { "value": "mie-MIENT", "name": "Nuevo Testamento en mixteco de Ocotepec", "lang_name": "Mixtec: Ocotepec" },
    { "value": "mig-MIGNT", "name": "Testamento jaa maa jitoho-yo Jesucristo", "lang_name": "Mixtec: San Miguel El Grande" },
    { "value": "mih-MIHNT", "name": "Tuhun Ndyoo sihin tyehen ñi", "lang_name": "Mixtec: Chayuco" },
    { "value": "mil-MILNT", "name": "Tnúhu ní cáháⁿ yǎ ndiǒxí xito cùu uú", "lang_name": "Mixtec: Peñoles" },
    { "value": "mio-MIONT", "name": "Tutu chaa cha iyo cuenda ra hahnu Jesucristo", "lang_name": "Mixtec: Pinotepa Nacional" },
    { "value": "mir-MIRNT", "name": "El Nuevo Testamento en mixe de Guichicovi", "lang_name": "Mixe: Isthmus" },
    { "value": "mit-MITNT", "name": "Ley saa ni nacoo Jesucristu", "lang_name": "Mixtec: Southern Puebla" },
    { "value": "miz-MIZNT", "name": "Tūʼún xuva kō vatā ó ntákaʼan ña ñuú Coatzospan", "lang_name": "Mixtec: Coatzospan" },
    { "value": "mjc-MJCNT", "name": "Tuhun tsaa tsa nacoo̱ jutu mañi yo Jesucristo tsi yo", "lang_name": "Mixtec: San Juan Colorado" },
    { "value": "mks-MKSNT", "name": "Tu̱hun sa̱á ña̱ na̱jándacoo Jesucristo nu̱ yo̱: El Nuevo Testamento en el mixteco de Silacayoapan", "lang_name": "Mixtec: Silacayoapan " },
    { "value": "mop-MOPNT", "name": "Le'ec Ada' U T'an A Dios A Tumulbene", "lang_name": "Mopán Maya" },
    { "value": "mpm-MPMNT", "name": "Nuevo Testamento en mixteco de Yosondúa", "lang_name": "Mixtec: Yosondúa" },
    { "value": "mpp-MPPPOR", "name": "Wapongte hibi: Luka, Salecebaicne, nga Galata", "lang_name": "Migabac" },
    { "value": "mqb-MQBNT", "name": "Aɓan 'am wiya awan", "lang_name": "Mbuko" },
    { "value": "mqj-MQJNT", "name": "Buku Masero: Pa'dandi Bakaru", "lang_name": "Mamasa" },
    { "value": "mti-MTINT", "name": "Gae Mataiwa", "lang_name": "Maiwa (Papua New Guinea)" },
    { "value": "mto-MTONT", "name": "Ya̱ʼa̱ tseʼe je̱ nam ko̱jtstán juuʼ veʼe je̱ Nteʼyamˍ xyaktaajnjimdu je̱ nMa̱j Vintsá̱namda Jesucristo ka̱jx", "lang_name": "Mixe: Totontepec" },
    { "value": "mxb-MXBNT", "name": "Tuti yó'o kúú to̱'on Ndios, ta xí'o ña kuendá sa'a̱ Jesús", "lang_name": "Mixtec: Tezoatlán " },
    { "value": "mxp-MXPNT", "name": "Ja øgyajpxy ja ømyadya̱ʼa̱ky midi xukpa̱a̱jtɨmp ja nɨtsoʼokʼajtɨn", "lang_name": "Tlahuitoltepec Mixe" },
    { "value": "mxq-MXQNT", "name": "Ja jembyʉ kajxy'átypyʉ mʉdʉ Jesukristʉkyʉjxm: El Nuevo Testamento de nuestro Señor Jesucristo en el mixe de Juquila", "lang_name": "Mixe: Juquila" },
    { "value": "mxt-MXTNT", "name": "Tuhun cha sañahá ra Jesucristo chi yo", "lang_name": "Mixtec: Jamiltepec" },
    { "value": "myu-MYUNT", "name": "Deus ekawẽntup Kawẽn iisuat ekawẽn", "lang_name": "Mundurukú" },
    { "value": "nab-NABNT", "name": "Txa²wã¹sũ̱³na² Wãn³txa²", "lang_name": "Southern Nambikuára" },
    { "value": "nch-NCHBI", "name": "Icamanal toteco; Santa Biblia", "lang_name": "Central Huasteca Nahuatl" },
    { "value": "ncj-NCJNT", "name": "In yancuic mononotzalistli ica Totecohtzin Jesucristo", "lang_name": "Northern Puebla Nahuatl" },
    { "value": "ncl-NCLNT", "name": "Ilajtulisli Yancuic toTata Jesucristo", "lang_name": "Michoacán Nahuatl" },
    { "value": "ncu-NCUNT", "name": "Abware̱se̱ŋ Wo̱re̱-ɔ", "lang_name": "Chumburung" },
    { "value": "ngu-NGUNT", "name": "In yencuic iyectlajtoltzin Dios itech ica toTeco Jesucristo", "lang_name": "Guerrero Nahuatl" },
    { "value": "nhe-NHEBI", "name": "Itlajtol toteco: Santa Biblia", "lang_name": "Eastern Huasteca Nahuatl" },
    { "value": "nhe-NHENT", "name": "Ya ni nopa yancuic tlajtoli tlen toteco toca mocajtoc; El Nuevo Testamento de nuestro Señor Jesucristo en el náhuatl de la Huasteca Oriental", "lang_name": "Eastern Huasteca Nahuatl" },
    { "value": "nhg-NHGNT", "name": "El Nuevo Testamento en nahuatl de Tetelcingo", "lang_name": "Tetelcingo Nahuatl" },
    { "value": "nhi-NHINT", "name": "In Yancuic Tlahtolsintilil", "lang_name": "Zacatlán-Ahuacatlán-Tepetzintla Nahuatl" },
    { "value": "nhu-NHUNT", "name": "Ŋwa' Nyo' Moŋkan mo Monfɛm", "lang_name": "Noone" },
    { "value": "nhw-NHWBI", "name": "Icamanal toteco; Santa Bíblia", "lang_name": "Western Huasteca Nahuatl" },
    { "value": "nhy-NHYNT", "name": "Itlajtol totajtzin Dios = El Nuevo Testamento", "lang_name": "Northern Oaxaca Nahuatl" },
    { "value": "nko-NKONT", "name": "Bulu ntam pɔpwɛ; Nkonya", "lang_name": "Nkonya" },
    { "value": "nop-NOPNTPO", "name": "Bepaŋ'walaŋ yofolok kobuli tiŋa kap", "lang_name": "Numanggang" },
    { "value": "not-NOTNT", "name": "Irinibare Tosorintsi Ocomantëgotëri Antigomi Jesoquirisito", "lang_name": "Nomatsiguenga" },
    { "value": "npl-NPLNT", "name": "Itlajtol Totajtsi Dios", "lang_name": "Southeastern Puebla Nahuatl" },
    { "value": "nsn-NSNNT", "name": "O uelhire uaia", "lang_name": "Nehan" },
    { "value": "ntp-NTPNT", "name": "Diuusi ñiooquidʌ utuducami oodamicʌdʌ", "lang_name": "Northern Tepehuan" },
    { "value": "nwi-NWINT", "name": "Nəkwəkwə imərhakə kape kughen: nɨrpenien vi", "lang_name": "Southwest Tanna" },
    { "value": "obo-OBONT", "name": "Moppiyon Dinoggan, Moka-atag ki Disas Krays", "lang_name": "Obo Manobo" },
    { "value": "ood-OODNT", "name": "Jiosh Wechij O'ohana", "lang_name": "Tohono O'odham" },
    { "value": "ote-OTENT", "name": "Ra 'Ra'yo Testamento", "lang_name": "Mezquital Otomi" },
    { "value": "otm-OTMNT", "name": "Ra ʼdaʼyonhogui nangue ma Hmuhʉ ra Jesucristo", "lang_name": "Eastern Highland Otomi" },
    { "value": "otn-OTNNT", "name": "Ja ua ra̱ ʼdaʼyo cohi bi gomi̱ Oja̱ yø ja̱ʼi̱", "lang_name": "Tenango Otomi" },
    { "value": "otq-OTQNT", "name": "Àr 'ra'yo nkohi Jö har ñhöñhö maxei nto̱ngwi ár mahwifi har ha̱i m'onda ne har ñhömfo̱", "lang_name": "Querétaro Otomi" },
    { "value": "ots-OTSNT", "name": "El Nuevo Testamento en otomí de San Felipe Santiago, Edo. de México", "lang_name": "Estado de México Otomi" },
    { "value": "pab-PABNT", "name": "Waitare Wenati Aho", "lang_name": "Parecís" },
    { "value": "pad-PADNT", "name": "Deus Athi Kapapirani Hida", "lang_name": "Paumarí" },
    { "value": "pah-PAHNT", "name": "Tupanaʼga nhiʼig̃a", "lang_name": "Tenharim" },
    { "value": "pao-PAONT", "name": "Te Naa Besa Unnepu", "lang_name": "Northern Paiute" },
    { "value": "pbb-PBBNT", "name": "Dyus Yuwe U'sesa", "lang_name": "Páez" },
    { "value": "pib-PIBNT", "name": "Gerotu Tokanchi Gipiratkaluru", "lang_name": "Yine" },
    { "value": "pio-PIONT", "name": "El Nuevo Testamento de nuestro Señor Jesucristo en el idioma piapoco", "lang_name": "Piapoco" },
    { "value": "pir-PIRNT", "name": "Cohãcjʉ̃ Yere Yahuducuri Tju", "lang_name": "Piratapuyo" },
    { "value": "pls-PLSNT", "name": "Tti jian joajné Jesucristo", "lang_name": "San Marcos Tlalcoyalco Popoloca" },
    { "value": "poe-POENT", "name": "Tí Nuevo Testamento cuènte Inchéni Jesucristo Cʼóna Nquìva", "lang_name": "San Juan Atzingo Popoloca" },
    { "value": "poh-POHNT", "name": "Reꞌ Lokꞌ Laj Hu̱j Wilic wi̱ꞌ Ribiral i Jesus", "lang_name": "Poqomchi'" },
    { "value": "poi-POINT", "name": "Jém jomipɨc trato jém iwatnewɨɨp tánomi Jesucristo", "lang_name": "Highland Popoluca" },
    { "value": "por-NTLH", "name": "Nova Tradução na Linguagem de Hoje", "lang_name": "Português" },
    { "value": "prf-PRFNT", "name": "En Maganda A Bareta Biblia", "lang_name": "Paranan" },
    { "value": "pri-PRINT", "name": "Tii Pwicîri: Âmu Aamwari naa na cî", "lang_name": "Paicî" },
    { "value": "quc-QUCNNT", "name": "Ru Loqꞌ Pixabꞌ Ri Dios", "lang_name": "K'iche'" },
    { "value": "quc-QUCTNT", "name": "Ru Lokꞌ Pixab Ri Dios", "lang_name": "K'iche'" },
    { "value": "quf-QUFNT", "name": "Mushuq Testamento", "lang_name": "Quechua: Lambayeque" },
    { "value": "quh-QUHNT", "name": "Dios Parlapawanchej", "lang_name": "Uralan Buliwya runasimi" },
    { "value": "qul-QULNT", "name": "Mosoj Testamento", "lang_name": "Quechua: North Bolivian" },
    { "value": "qup-QUPNT", "name": "Yaya Diospa mushu killkachishkan shimi", "lang_name": "Quechua: Southern Pastaza" },
    { "value": "qvc-QVCNT", "name": "Mushuq Tistamintu", "lang_name": "Quechua: Cajamarca" },
    { "value": "qve-QVENT", "name": "Mosoq Testamento", "lang_name": "Quechua: Eastern Apurimac" },
    { "value": "qvh-QVHNT", "name": "Mushog Testamento", "lang_name": "Quechua: Huamalíes-Dos de Mayo Huánuco" },
    { "value": "qvm-QVMNT", "name": "Mushog Testamento", "lang_name": "Quechua: Margos-Yarowilca-Lauricocha" },
    { "value": "qvn-QVNNT", "name": "Tayta Diospa Guepacag Testamentun", "lang_name": "Quechua: North Junín" },
    { "value": "qvs-QVSNT", "name": "Tata Diospa Mushuk Rimanan", "lang_name": "Quechua: San Martín" },
    { "value": "qvw-QVWNT", "name": "Muśhü limalicuy", "lang_name": "Quechua: Huaylla Wanca" },
    { "value": "qvz-QVZNT", "name": "Diospa shimi", "lang_name": "Quicua: Northern Pastaza" },
    { "value": "qwh-QWHNT", "name": "Teyta Diospa Mushoq Testamentun", "lang_name": "Quechua: Huaylas Ancash" },
    { "value": "qxh-QXHNT", "name": "Mushug Testamento", "lang_name": "Quechua: Panao Huánuco" },
    { "value": "qxn-QXNNT", "name": "Señor Jesucristopa alli willacuynin", "lang_name": "Northern Conchucos Ancash Quechua" },
    { "value": "qxo-QXONT", "name": "Mushog Testamento", "lang_name": "Southern Conchucos Ancash Quechua" },
    { "value": "rkb-RKBNT", "name": "Deus Harere Aibaky Sesus mymyspirikpoko naha", "lang_name": "Rikbaktsa" },
    { "value": "sab-SABNT", "name": "Chube gerua jagere Jesucristo giti degaba kwian ulita alin: El Nuevo Testamento de nuestro Señor Jesucristo en el idioma buglere", "lang_name": "Buglere" },
    { "value": "sey-SEYNT", "name": "Maija'quë Huajë Ca Nëose'e", "lang_name": "Secoya" },
    { "value": "sgz-SGZNT", "name": "Hutngin Kamkabat si Klu ", "lang_name": "Sursurunga" },
    { "value": "shp-SHPNTPO", "name": "Diossen joi jatíxonbi onanti joi", "lang_name": "Shipibo-Conibo" },
    { "value": "sja-SJANT", "name": "Tachi ak'õre pedee", "lang_name": "Epena" },
    { "value": "smk-SMKNT", "name": "Si Biblia", "lang_name": "Bolinao" },
    { "value": "snn-SNNNT", "name": "Riusu cocabera: mai ëjaguë Jesucristo  ba'iyete toyani jo'case'e'ë", "lang_name": "Siona" },
    { "value": "spa-DHH", "name": "Biblia Dios Habla Hoy (sin notas ni ayudas)", "lang_name": "Español" },
    { "value": "spa-RVR1960", "name": "Biblia Reina Valera 1960", "lang_name": "Español" },
    { "value": "spy-SPYNT", "name": "Biibilya Nyēē Tiliil", "lang_name": "Kalenjin" },
    { "value": "srm-SRMNT", "name": "Gadu Buku", "lang_name": "Saramaccan" },
    { "value": "srn-SRNNT", "name": "Nyun Testamenti", "lang_name": "Sranan Tongo" },
    { "value": "srq-SRQNT", "name": "Mbia Cheẽ", "lang_name": "Sirionó" },
    { "value": "ssg-SSGNT", "name": "Kakai Haeu", "lang_name": "Seimat" },
    { "value": "stp-STPNT", "name": "Gu ñio'ki'ñ gu Dios na bhaan tu a'ga guch xoi'kam", "lang_name": "Southeastern Tepehuan" },
    { "value": "suz-SUZBI", "name": "परमप्रभु यावे आ लोव़", "lang_name": "Sunwar" },
    { "value": "sxb-SXBNT", "name": "Endagano Empia", "lang_name": "Suba" },
    { "value": "tac-TACNT", "name": "Onorúgame nila ra'íchali", "lang_name": "Lowland Tarahumara" },
    { "value": "tbg-TBGNTPO", "name": "Qaraaka uva tivatora", "lang_name": "North Tairora" },
    { "value": "tbl-TBLNT", "name": "Udél dwata: gna kesfasad ne lomi kesfasad", "lang_name": "Tboli" },
    { "value": "tca-TCANT", "name": "Tupanaarü Ore i Tórü Cori ya Ngechuchu ya Cristuchiga", "lang_name": "Ticuna" },
    { "value": "tee-TEENT", "name": "Ixchivinti Dios", "lang_name": "Huehuetla Tepehua" },
    { "value": "ter-TERNT", "name": "Emo'u Itukó'oviti", "lang_name": "Tereno" },
    { "value": "tku-TKUNT", "name": "Xasāstiʼ testamento (Xatze tachihuīn ixpālacata Jesucristo)", "lang_name": "Upper Necaxa Totonac" },
    { "value": "tna-TNANT", "name": "Diusu sa mimi", "lang_name": "Tacana" },
    { "value": "toc-TOCNT", "name": "Xasasti talacaxlan", "lang_name": "Coyutla Totonac" },
    { "value": "toj-TOJNT", "name": "Ja yajcʼachil testamento sbaj ja cajualtic Jesucristo", "lang_name": "Tojolabal" },
    { "value": "too-TOONT", "name": "Huan Xasāstiʼ testamento: Huan xatzey tachihuīn ixpālacata Jesucristo", "lang_name": "Xicotepec De Juárez Totonac" },
    { "value": "top-TOPNT", "name": "Xasasti talaccaxlan", "lang_name": "Papantla Totonac" },
    { "value": "tos-TOSNT", "name": "Hua̱ xasa̱sti talacca̱xlan quinTla̱tican Jesucristo", "lang_name": "Highland Totonac" },
    { "value": "tpt-TPTNT", "name": "Ixchivinti Dios: ni sastʼi chivinti yu Dios jatʼatamakaul ixlapanakni laka lhimasipijni", "lang_name": "Tlachichilco Tepehua" },
    { "value": "trc-TRCNT", "name": "Se-nānā Diosē nanā sāʼ me rá catūū nimán níʼ a", "lang_name": "Copala Triqui" },
    { "value": "tsw-TSWNT", "name": "Nzuwulai n Sa'avu na̱ Tsishingini na̱ a̱ɗiva̱ a na a ɗangulai a Nzuwulai mu Ufaru", "lang_name": "Tsishingini" },
    { "value": "ttc-TTCNT", "name": "Te akʼaʼj tuʼjal tuj tuʼjal qtata Dios", "lang_name": "Tektiteko" },
    { "value": "tuc-TUCNT", "name": "Maaron Saveeŋ Tooni Patabuyaaŋ", "lang_name": "Mutu" },
    { "value": "tuc-TUCONT", "name": "Maaron Saveeŋ Toni Patabuaŋ", "lang_name": "Mutu" },
    { "value": "tuo-TUONT", "name": "Õ'âkĩ̶ hɨ yeere uúkũri turi Tukano", "lang_name": "Tucano" },
    { "value": "txu-TXUNT", "name": "Metĩndjwỳnh Kute Memã Kabẽn Ny Jarẽnh", "lang_name": "Kayapó" },
    { "value": "tzj-TZJNT", "name": "Cꞌacꞌ Chuminem", "lang_name": "Tz'utujil" },
    { "value": "tzo-TZONT", "name": "Jaʼ ti achʼ Testamento: jaʼ scʼopilal ti Jesucristoe jaʼ ti Jcoltavanej cuʼuntique (El Nuevo Testamento de nuestro señor Jesucristo en Tzotzil de Huixtán)", "lang_name": "Tzotzil" },
    { "value": "tzo-TZOZNT", "name": "Sc'op riox: ja' li' yaloj ti chac' jcuxlejaltic ta sbatel osli ti cajvaltic Jesucristoe", "lang_name": "Tzotzil" },
    { "value": "ura-URANT", "name": "Cana Coaunera Ere", "lang_name": "Urarina" },
    { "value": "urb-URBNT", "name": "Tupã Je'ẽha", "lang_name": "Kaapor" },
    { "value": "usp-USPNT", "name": "Lok'laj Jyolj Kakaj Dios", "lang_name": "Uspanteco" },
    { "value": "vmy-VMYNT", "name": "El Nuevo Testamento Mazateco de Ayautla", "lang_name": "Ayautla Mazatec" },
    { "value": "wap-WAPNT", "name": "Kaimana'o Tominkaru Paradan", "lang_name": "Wapishana" },
    { "value": "xav-XAVNT", "name": "'Re ĩhâimana u'âsi mono zadawa wasu'u", "lang_name": "Xavánte" },
    { "value": "xtd-XTDNT", "name": "Tnuʼu vaʼa tnuʼu Jesucristo", "lang_name": "Mixtec: Diuxi-Tilantongo" },
    { "value": "xtm-XTMNTPP", "name": "Tnu'u vii tnu'u va'a Su'si ma", "lang_name": "Mixtec: Magdalena Peñasco" },
    { "value": "yaa-YAANT", "name": "Niospa meka fena Jesucristoõnoa", "lang_name": "Yaminahua" },
    { "value": "yad-YADNT", "name": "Ju̱denu jto̱ nijya̱nvamyu", "lang_name": "Yagua" },
    { "value": "yaq-YAQNT", "name": "Yoʼowe Jesukrijtota itom yaʼariakaʼu betchiʼbo juʼu bemelaka liojta betana lutuʼuria yaʼari (El Nuevo Testamento en yaqui)", "lang_name": "Yaqui" },
    { "value": "yut-YUTNT", "name": "Piŋkop Gen", "lang_name": "Yopno" }];
